In [20]:
%pip install pyscisci networkx python-Levenshtein sparse_dot_topn matplotlib boto3 widgetsnbextension ipywidgets "dask[distributed]" --upgrade

Requirement already satisfied: pyscisci in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (0.8.11)
Requirement already satisfied: networkx in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (3.2.1)
Requirement already satisfied: python-Levenshtein in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (0.25.0)
Requirement already satisfied: sparse_dot_topn in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (1.0.0)
Requirement already satisfied: matplotlib in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (3.8.3)
Requirement already satisfied: boto3 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (1.34.49)
Collecting boto3
  Downloading boto3-1.34.52-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: widgetsnbextension in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (4.0.10)
Requirement already satisfied: ipywidgets in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (8.1.2)
Requirement already satisfied: dask[distributed] in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (2024.2.1)
Requirement already satisfied: pandas in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (2.1.4)
Requirement already satisfied: numpy in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (1.26.3)
Requirement already satisfied: scipy in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (1.11.4)
Requirement already satisfied: scikit-learn in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (1.3.2)
Requirement already satisfied: nameparser in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (1.1.3)
Requirement already satisfied: lxml in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (5.1.0)
Requirement already satisfied: requests in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (2.31.0)
Requirement already satisfied: unidecode in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (1.3.8)
Requirement already satisfied: tqdm in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (4.66.1)
Requirement already satisfied: numba in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pyscisci) (0.59.0)
Requirement already satisfied: Levenshtein==0.25.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from python-Levenshtein) (0.25.0)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.1.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from Levenshtein==0.25.0->python-Levenshtein) (3.6.1)
Requirement already satisfied: psutil in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from sparse_dot_topn) (5.9.7)
Requirement already satisfied: contourpy>=1.0.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Collecting botocore<1.35.0,>=1.34.52 (from boto3)
  Downloading botocore-1.34.52-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from boto3) (0.10.0)
Requirement already satisfied: comm>=0.1.3 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython>=6.1.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipywidgets) (8.20.0)
Requirement already satisfied: traitlets>=4.3.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipywidgets) (5.14.1)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipywidgets) (3.0.10)
Requirement already satisfied: click>=8.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (8.1.7)
Requirement already satisfied: cloudpickle>=1.5.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (2024.2.0)
Requirement already satisfied: partd>=1.2.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (1.4.1)
Requirement already satisfied: pyyaml>=5.3.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (6.0.1)
Requirement already satisfied: toolz>=0.10.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (7.0.1)
Requirement already satisfied: distributed==2024.2.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from dask[distributed]) (2024.2.1)
Requirement already satisfied: jinja2>=2.10.3 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (3.1.3)
Requirement already satisfied: locket>=1.0.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (1.0.0)
Requirement already satisfied: msgpack>=1.0.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (1.0.7)
Requirement already satisfied: sortedcontainers>=2.0.5 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (3.0.0)
Requirement already satisfied: tornado>=6.0.4 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (6.4)
Requirement already satisfied: urllib3>=1.24.3 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (2.0.7)
Requirement already satisfied: zict>=3.0.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from distributed==2024.2.1->dask[distributed]) (3.0.0)
Requirement already satisfied: zipp>=0.5 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from importlib-metadata>=4.13.0->dask[distributed]) (3.17.0)
Requirement already satisfied: decorator in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.17.2)
Requirement already satisfied: stack-data in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: exceptiongroup in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: pexpect>4.3 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: six>=1.5 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from numba->pyscisci) (0.42.0)
Requirement already satisfied: pytz>=2020.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pandas->pyscisci) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pandas->pyscisci) (2023.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from requests->pyscisci) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from requests->pyscisci) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from requests->pyscisci) (2023.11.17)
Requirement already satisfied: joblib>=1.1.1 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from scikit-learn->pyscisci) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from scikit-learn->pyscisci) (3.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from jinja2>=2.10.3->distributed==2024.2.1->dask[distributed]) (2.1.5)
Requirement already satisfied: ptyprocess>=0.5 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in /disks/qnap2/notebook/t-yatima/.venv/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Downloading boto3-1.34.52-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 8.7 MB/s eta 0:00:00
Downloading botocore-1.34.52-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 62.4 MB/s eta 0:00:0000:010:01
Installing collected packages: botocore, boto3
  Attempting uninstall: botocore
    Found existing installation: botocore 1.34.49
    Uninstalling botocore-1.34.49:
      Successfully uninstalled botocore-1.34.49
  Attempting uninstall: boto3
    Found existing installation: boto3 1.34.49
    Uninstalling boto3-1.34.49:
      Successfully uninstalled boto3-1.34.49
Successfully installed boto3-1.34.52 botocore-1.34.52

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pyscisci.all as pyscisci

import os
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

import dask.dataframe as dd

%matplotlib inline

path2openalex = '/disks/qnap2/data/t-yatima/openalex231124/data/'

DATA_DIR = '/disks/qnap2/data/t-yatima/scisciJP2024_tutorial/'
OUTPUT_WORKS_DF_PKL = DATA_DIR + 'random_works_large_df.pkl'
OUTPUT_WORKS_REL_REF_DF_PKL = DATA_DIR + 'random_rel_ref_large_df.pkl'

myoa = pyscisci.OpenAlex(path2openalex, database_extension='csv.gz', keep_in_memory=True, show_progress=True, enable_dask=True) 

from dask.diagnostics import ProgressBar
ProgressBar().register()

from dask.distributed import progress

In [2]:
all_pub_ddf = myoa.load_publications()
all_pub_ddf

Loading Publications:   0%|          | 0/480 [00:00<?, ?it/s]

Dask DataFrame Structure:
                PublicationId JournalId    Year NumberCitations   Title    Date DocType     Doi    PMID  Volume   Issue FirstPage LastPage IsRetracted IsParaText
npartitions=480
                       object    object  object          object  object  object  object  object  object  object  object    object   object      object     object
                          ...       ...     ...             ...     ...     ...     ...     ...     ...     ...     ...       ...      ...         ...        ...
...                       ...       ...     ...             ...     ...     ...     ...     ...     ...     ...     ...       ...      ...         ...        ...
                          ...       ...     ...             ...     ...     ...     ...     ...     ...     ...     ...       ...      ...         ...        ...
                          ...       ...     ...             ...     ...     ...     ...     ...     ...     ...     ...       ...      ...         ...        ...
Dask Name: concat, 7077 graph layers

In [3]:
# 9min
references_df = myoa.load_references()
display(references_df)

Loading pub2ref:   0%|          | 0/480 [00:00<?, ?it/s]

        CitingPublicationId CitedPublicationId
0                3117235547           55183993
1                3117235547          657382535
2                3117235547         1540739244
3                3117235547         1582266453
4                3117235547         1642177666
...                     ...                ...
9436475          2134809571         2090594024
9436476          2134809571         2124054840
9436477          2134809571         2147932722
9436478          2134809571         2158145285
9436479          2134809571         4235794113

[1683280953 rows x 2 columns]

In [4]:
references_df[references_df['CitingPublicationId'] == 2133895471]

Empty DataFrame
Columns: [CitingPublicationId, CitedPublicationId]
Index: []

In [5]:
references_df[references_df['CitedPublicationId'] == 2133895471]

         CitingPublicationId CitedPublicationId
2382733           2133634407         2133895471
166217              65896575         2133895471
61526             2180197584         2133895471
1910930           2064783168         2133895471
7965554           1510389535         2133895471
8956457           2030085258         2133895471
209772            2012904459         2133895471
3971004           2060282627         2133895471
7427693           1502129278         2133895471
7615629           2074890356         2133895471
73350             3129179664         2133895471
3635227           2101852508         2133895471
8129834           2032764238         2133895471
9398387           1996701608         2133895471
7726358           2034237009         2133895471
1568881           2028516245         2133895471
7865134           2005687467         2133895471
5015250             84942274         2133895471
4108533           2169772764         2133895471
2819550           2005928378         2133895471
5022040           1964998843         2133895471
4348437           1982551706         2133895471
8147031           2097851686         2133895471
3200721           2041099984         2133895471
282577            2160890391         2133895471
3629414             41800138         2133895471
7580145           2143073814         2133895471
8540164           1969661090         2133895471
8328814           2090982438         2133895471
3211024           2560504615         2133895471
5673615             84994331         2133895471
6428991           2029466440         2133895471
7801885           2787336147         2133895471
6441711           2610438241         2133895471
7208198           2956159809         2133895471
5029648           3041156154         2133895471
6370045           4211056068         2133895471
2359498           2195580779         2133895471
2478224           2096695442         2133895471
4806773           2011802583         2133895471
6263592           2149204948         2133895471
284427            1997396577         2133895471
529976            2900983372         2133895471
5497585           1991378672         2133895471
537385            1524229752         2133895471
5338918           3196801363         2133895471
153756            3133985709         2133895471
12213781           182659067         2133895471
7090572           2039326242         2133895471
1486649           2149221003         2133895471

In [6]:
# 8min
random_works_ddf = all_pub_ddf.sample(frac=0.002, random_state=1)
random_works_df = random_works_ddf.compute()

[########################################] | 100% Completed | 557.45 s

In [7]:
random_works_df

,PublicationId,JournalId,Year,NumberCitations,Title,Date,DocType,Doi,PMID,Volume,Issue,FirstPage,LastPage,IsRetracted,IsParaText
346,3187609235,NaN,2020,0,Des choix contraires à la transition écologiqu...,2020-01-01,article,NaN,NaN,NaN,85,46,46,False,False
237,2266400421,NaN,1989,0,Ballade pour Frédéric. Piano,1989-01-01,article,NaN,NaN,NaN,NaN,NaN,NaN,False,False
84767,2242094754,NaN,2005,0,Understanding what child protection data mean:...,2005-08-11,article,NaN,NaN,NaN,NaN,NaN,NaN,False,False
183235,2951317825,NaN,2015,0,Desvendando o Universo com o Céu da Serra Gaúcha,2015-11-30,article,NaN,NaN,3,3,NaN,NaN,False,False
198349,3030572269,NaN,2018,0,The estrogen deficiency hypothesis of schizoph...,2018-12-05,article,10.3760/cma.j.issn.1006-7884.2018.06.010,NaN,51,6,385,388,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306631,1698120224,NaN,2002,25,NaN,2002-01-01,article,10.1023/a:1020616324734,NaN,69,3,897,904,False,False
214283,2024816949,NaN,2011,27,A Quality-of-Life Comparison Between Self-Alig...,2011-04-01,article,10.1563/aaid-joi-d-10-00070,20662674,37,sp1,167,173,False,False
321944,2040609328,NaN,1961,25,INFRARED STUDIES ON PYRROLES. THE STRUCTURE OF...,1961-04-01,article,10.1021/j100822a008,NaN,65,4,624,628,False,False
251443,124423791,NaN,1986,26,Paleomagnetism in Arcuate Mountain Belts,1986-01-01,book-chapter,10.1016/b978-0-444-42688-8.50012-6,NaN,NaN,NaN,141,158,False,False
280047,2119546324,NaN,1971,26,ANTI-EMETIC AND PROPULSIVE PERISTALTIC PROPERT...,1971-04-01,article,10.1093/bja/43.4.400,4930207,43,4,400,403,False,False

In [8]:
# 11min
all_paa = myoa.load_publicationauthoraffiliation()
all_paa

Loading Publication Author Affiliation:   0%|          | 0/480 [00:00<?, ?it/s]

/home/t-yatima/t-yatima/.venv/lib/python3.10/site-packages/pyscisci/datasource/readwrite.py:203: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat(data)

,PublicationId,AuthorId,AffiliationId,AuthorSequence,OrigAuthorName
0,4287754650,5062226449,NaN,1,Enrico Biffis
1,4287754650,5033140346,NaN,2,Erik Chavez
2,4287754650,5061623148,NaN,3,Alexis Louaas
3,4287754650,5074952038,NaN,4,Pierre M. Picard
4,4287938432,5045351019,NaN,1,Arthur Hugeat
...,...,...,...,...,...
1810902,2134809571,5004197195,1.355989e+08,3,Hiroki Shibata
1810903,2134809571,5061432587,4.210123e+09,4,Tomomi Saito
1810904,2134809571,5029531503,4.240550e+07,5,Osamu Doi
1810905,2134809571,5004358248,4.240550e+07,6,Yutaka Ohya
1810906,2134809571,5011973675,4.240550e+07,7,Norio Yoshizaki

In [9]:
# all_paaでPublicationIdごとにAuthorIdの数を数える
all_paa.drop(columns=['AffiliationId', 'AuthorSequence', 'OrigAuthorName'], inplace=True)
author_count = all_paa.groupby('PublicationId').count().reset_index()
author_count.columns = ['PublicationId', 'AuthorCount']  # 列名を変更

# random_works_dfに結果を結合する
random_works_df = random_works_df.merge(author_count, on='PublicationId', how='left')
random_works_df

,PublicationId,JournalId,Year,NumberCitations,Title,Date,DocType,Doi,PMID,Volume,Issue,FirstPage,LastPage,IsRetracted,IsParaText,AuthorCount
0,3187609235,NaN,2020,0,Des choix contraires à la transition écologiqu...,2020-01-01,article,NaN,NaN,NaN,85,46,46,False,False,2.0
1,2266400421,NaN,1989,0,Ballade pour Frédéric. Piano,1989-01-01,article,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.0
2,2242094754,NaN,2005,0,Understanding what child protection data mean:...,2005-08-11,article,NaN,NaN,NaN,NaN,NaN,NaN,False,False,2.0
3,2951317825,NaN,2015,0,Desvendando o Universo com o Céu da Serra Gaúcha,2015-11-30,article,NaN,NaN,3,3,NaN,NaN,False,False,4.0
4,3030572269,NaN,2018,0,The estrogen deficiency hypothesis of schizoph...,2018-12-05,article,10.3760/cma.j.issn.1006-7884.2018.06.010,NaN,51,6,385,388,False,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455434,1698120224,NaN,2002,25,NaN,2002-01-01,article,10.1023/a:1020616324734,NaN,69,3,897,904,False,False,3.0
455435,2024816949,NaN,2011,27,A Quality-of-Life Comparison Between Self-Alig...,2011-04-01,article,10.1563/aaid-joi-d-10-00070,20662674,37,sp1,167,173,False,False,4.0
455436,2040609328,NaN,1961,25,INFRARED STUDIES ON PYRROLES. THE STRUCTURE OF...,1961-04-01,article,10.1021/j100822a008,NaN,65,4,624,628,False,False,2.0
455437,124423791,NaN,1986,26,Paleomagnetism in Arcuate Mountain Belts,1986-01-01,book-chapter,10.1016/b978-0-444-42688-8.50012-6,NaN,NaN,NaN,141,158,False,False,2.0
455438,2119546324,NaN,1971,26,ANTI-EMETIC AND PROPULSIVE PERISTALTIC PROPERT...,1971-04-01,article,10.1093/bja/43.4.400,4930207,43,4,400,403,False,False,2.0

In [10]:
bibmet_id_list = [int(work) for work in random_works_df['PublicationId'].to_list()]
bibmet_id_list

[3187609235,
 2266400421,
 2242094754,
 2951317825,
 3030572269,
 353247501,
 423748994,
 3140467897,
 600221648,
 600340109,
 1129359357,
 806319339,
 2011382101,
 418273658,
 1955343276,
 2261115044,
 593195327,
 2102983573,
 2904163544,
 2254226425,
 3213920623,
 3028340796,
 3197833236,
 333645419,
 2292987227,
 4300175606,
 586206721,
 1021614813,
 2369894610,
 561573473,
 597990456,
 179446277,
 1559185838,
 28721133,
 4318538264,
 4327593038,
 2500416614,
 2379598691,
 2098030745,
 3137758815,
 2269698071,
 2256635544,
 367615199,
 2372627520,
 2313657755,
 2070456871,
 2340998267,
 2283355807,
 75216325,
 3029494918,
 3028650866,
 3088404512,
 958653214,
 162361947,
 969464301,
 2299861510,
 2905853258,
 2921534856,
 641200500,
 2995043144,
 3032579228,
 411410270,
 423560238,
 2261032407,
 1488539424,
 611272427,
 4206311784,
 597022508,
 1929649835,
 573255590,
 75764502,
 4368372884,
 2369687867,
 2742025093,
 2302789741,
 62174780,
 268883542,
 139464679,
 2171183418,
 572150206,
 1600386863,
 2279479644,
 2616477608,
 949208802,
 1023226066,
 1173137689,
 2265616230,
 2121494174,
 2525914862,
 420523025,
 2235224002,
 2300972012,
 2750606519,
 935974642,
 3187126456,
 2741210803,
 2263468868,
 2314569901,
 1003025610,
 2593382399,
 618906235,
 2905568923,
 652571759,
 987758496,
 2377094041,
 2750401888,
 954890637,
 2598556092,
 1487954434,
 2012136074,
 1016838830,
 3116562372,
 3029972750,
 1008389078,
 2320545301,
 423908892,
 2993629898,
 258343024,
 2102068749,
 2751731276,
 566010699,
 2392890941,
 302576757,
 368480084,
 123799816,
 944715618,
 1963540192,
 652018070,
 3093389873,
 2794090920,
 1506926946,
 3046890000,
 3212976138,
 69231177,
 380002499,
 2312432189,
 2115774576,
 2506468437,
 370044721,
 2922470347,
 386930930,
 2389622827,
 2759446925,
 19723739,
 4312727193,
 2196375658,
 2191810903,
 2269187999,
 2360910412,
 603660398,
 371761959,
 2341692914,
 2165296796,
 2755920640,
 2349651923,
 2300946451,
 2599598605,
 986414917,
 172899021,
 2560663909,
 114734865,
 2363488062,
 1167326440,
 411732216,
 81448814,
 420363317,
 2538908481,
 962052019,
 2942412261,
 2102908330,
 2120077586,
 3144069927,
 386112578,
 3158642225,
 972141335,
 2562781565,
 3192909405,
 2808279538,
 2597846424,
 2901573093,
 599398147,
 2989716253,
 628555925,
 858709125,
 2338271223,
 2745507523,
 3032248611,
 904029795,
 2522068942,
 2487977523,
 1044320124,
 993451934,
 2380088941,
 606709749,
 417045850,
 2917068486,
 2797741388,
 2530141779,
 395900919,
 3001390901,
 1600543513,
 941463994,
 3004613216,
 652995946,
 2412168618,
 176864130,
 368276915,
 3187923300,
 2383032018,
 2209738442,
 2270335328,
 578112622,
 2071858127,
 3090858500,
 2981405060,
 2607824490,
 1228328716,
 2963677826,
 3126400126,
 607948555,
 567882843,
 1238677387,
 36180255,
 3165336974,
 2589652775,
 3181727441,
 2247194218,
 2749037783,
 426999487,
 2050334018,
 908235110,
 3166228410,
 775561754,
 976226391,
 1142119785,
 2790076226,
 2785067881,
 2279017680,
 2019384645,
 2245610768,
 616979756,
 1021685505,
 994417858,
 2560122216,
 2320443125,
 627378460,
 409830792,
 3199834718,
 4206222653,
 273900017,
 266843689,
 2743353189,
 1180137819,
 584438716,
 4291359597,
 4243613703,
 2368780105,
 2744128490,
 2586500627,
 377302834,
 397313086,
 1017482020,
 761798941,
 2296052862,
 590976650,
 3018785130,
 427133751,
 832898066,
 3150580770,
 972258455,
 608375021,
 939157613,
 387525681,
 992395693,
 2376870265,
 3168006239,
 2283688594,
 1889865880,
 399602282,
 982457154,
 314140631,
 2884345813,
 2370592512,
 1039318392,
 2750814085,
 595086589,
 593202638,
 653528043,
 2956118570,
 2162003275,
 1482099184,
 2220893185,
 1773452460,
 591441207,
 2292606494,
 2467482563,
 2516511326,
 1546601168,
 107618053,
 407543701,
 221962605,
 4387868126,
 3010833732,
 337163085,
 572560402,
 2769909591,
 119828077,
 1668370373,
 2486678820,
 2899959497,
 1606851286,
 3199771616,
 144764725,
 2474405524,
 3049009719,
 1180857508,
 1485855318,
 359625210,
 2753274739,
 315585495,
 173645435,
 1997638663,
 2924284146,
 367113584,
 3009583092,
 335528999,
 1495373174,
 382684775,
 2749318636,
 2336772381,
 2589427055,
 3134691269,
 3171370164,
 2745755645,
 2902520588,
 2288010224,
 1534937558,
 2206824140,
 2611310204,
 2773825915,
 112262676,
 961584823,
 408946685,
 383977630,
 4213135151,
 1020479850,
 2461855223,
 2528055987,
 1130489869,
 257621363,
 2897238584,
 1543867642,
 1516980441,
 2348730577,
 3215910296,
 984583859,
 438299386,
 3188874142,
 424839831,
 3193721051,
 659322934,
 3208515739,
 2801021377,
 1992371292,
 3042612312,
 2921803933,
 419142482,
 2593249417,
 2419593069,
 99061811,
 2225271113,
 2271618941,
 1602876373,
 3020242930,
 3037803539,
 418738647,
 354003591,
 4205962401,
 178535481,
 2279400418,
 3067262655,
 3147346189,
 2345551136,
 241525563,
 2892160193,
 411893640,
 367333667,
 308733680,
 1499685886,
 2551104353,
 3041788344,
 1026692916,
 1156399062,
 3190517703,
 3011615874,
 624704081,
 631434458,
 2758801797,
 2587810528,
 2148850393,
 576465310,
 3098622171,
 3138041070,
 1927753651,
 2040668314,
 2232779306,
 231598522,
 3162965482,
 426519163,
 799259385,
 4206810326,
 3080975850,
 3164315189,
 633920585,
 2362590214,
 602822817,
 3047168607,
 3166055645,
 2314714624,
 747833492,
 434487258,
 2289315993,
 2407675592,
 993050397,
 2533129642,
 2527322916,
 1923760505,
 8024469,
 3082914647,
 2751801159,
 924361412,
 1497720325,
 1011791445,
 2203997343,
 3017681055,
 2341846522,
 155891459,
 2602752072,
 1496147593,
 4312967885,
 1620848243,
 390122633,
 3035717783,
 584230871,
 14245246,
 2737286010,
 2376730369,
 1167978304,
 2936656685,
 4205721330,
 3149186013,
 2255786919,
 2386184151,
 2549238741,
 1591521843,
 644540353,
 2990731748,
 1588903292,
 1009884794,
 2354512795,
 1788893310,
 614735800,
 2892281596,
 304174363,
 391518526,
 2263445276,
 3190533470,
 2376153816,
 923952562,
 2569007892,
 567516812,
 2383410293,
 753949764,
 420738199,
 2754691101,
 1542558679,
 606907093,
 616294428,
 391670748,
 2529368914,
 650507651,
 2615554088,
 2256083513,
 49851048,
 420285775,
 2281828713,
 636066323,
 2016602336,
 2228658907,
 858657369,
 2911999839,
 2492050415,
 3210908416,
 2944799434,
 2796505927,
 3205500728,
 616726029,
 166029231,
 3015417160,
 2618028972,
 3014996269,
 47503362,
 1123396545,
 2793476671,
 1540190160,
 986141106,
 5987242,
 311057777,
 1982321632,
 2937630617,
 2243986980,
 4206843609,
 962274888,
 2281696405,
 377240803,
 962123250,
 1533232519,
 1973342244,
 408125740,
 1583400575,
 619403397,
 623466254,
 989154968,
 2233498946,
 3116487164,
 1037228888,
 624517362,
 382143064,
 2595708164,
 2257410624,
 105172821,
 1135503845,
 2025363782,
 294412389,
 383787822,
 3036960162,
 414921636,
 1601105660,
 2804403466,
 2742478335,
 2347285307,
 2947302135,
 3140939316,
 315392863,
 369440361,
 394335655,
 2775000175,
 2433634448,
 634442616,
 560974021,
 2563322326,
 2264286611,
 2775341068,
 1528392299,
 358053615,
 3093805534,
 2754300332,
 2320384929,
 930966059,
 2562529935,
 1500183682,
 2274799953,
 2539785385,
 378971786,
 165339455,
 364544938,
 1002749480,
 2977895753,
 3122131509,
 266505471,
 2805257713,
 2551759887,
 2625943676,
 746072746,
 2067832317,
 2390591641,
 1449324053,
 577242895,
 645485500,
 2891235231,
 597699569,
 2334136782,
 178323454,
 634664076,
 3005525242,
 3186482146,
 2347317707,
 1515363876,
 2338367584,
 184438576,
 2084581283,
 2317920173,
 1564047199,
 652758221,
 425126886,
 3092637244,
 383404206,
 4368359392,
 2768425978,
 2221869519,
 2011369541,
 3160285027,
 2233889806,
 3202059121,
 2008875487,
 3017323024,
 2268275819,
 888693220,
 617622463,
 788354128,
 2389590408,
 645680108,
 6357914,
 3178562006,
 2183885324,
 3105191849,
 982358848,
 2591757353,
 974071470,
 3109946792,
 983451786,
 387068764,
 2030937686,
 193156742,
 2993379010,
 2973687631,
 2407289231,
 2600273465,
 2724985922,
 2769387573,
 899060693,
 657838298,
 2475269158,
 2525494373,
 2751706255,
 2444685745,
 374842433,
 3040902080,
 2149759738,
 4312607973,
 2390167598,
 2029729977,
 1043404184,
 2243696521,
 2745705511,
 3163297976,
 4366958538,
 208294015,
 2138059056,
 354974154,
 426405003,
 2241500558,
 364448379,
 2740820645,
 980784926,
 2786516519,
 3082789303,
 369966874,
 2612930630,
 995631793,
 2357022323,
 2214212082,
 169353537,
 2979803817,
 2170217184,
 2332852995,
 2027815162,
 1993059412,
 2288244090,
 2482114918,
 2471221814,
 2055909729,
 2076327783,
 2134455278,
 2073739065,
 2047865380,
 2889443114,
 2444544129,
 2367233520,
 1998875271,
 1816790508,
 2349893302,
 2162778786,
 2323032971,
 1970908398,
 2083688121,
 2298064217,
 4224275439,
 2096425138,
 2093697132,
 2328190522,
 1582743933,
 4235069784,
 2479560160,
 2119585918,
 3162724938,
 1566629283,
 2075383954,
 4250883254,
 2318227003,
 2416937315,
 2247749927,
 2000980182,
 1943436787,
 2796914320,
 1993928186,
 2100458557,
 2062714468,
 24527347,
 2021183686,
 2592095775,
 2126161869,
 2916637224,
 2161254395,
 1999868121,
 1813534488,
 2384546741,
 2589295893,
 2165749097,
 2069954996,
 2961852181,
 1991792755,
 2489311201,
 2954198808,
 2048190353,
 4249165465,
 2094305090,
 2323053531,
 2231435673,
 2269181351,
 4240315047,
 2607104641,
 2040888273,
 2274619368,
 2374330482,
 2806911549,
 4250301210,
 2607889203,
 2156024342,
 2784113061,
 2036275883,
 2112315065,
 2112924340,
 1530559219,
 4255827847,
 2559725817,
 2120599892,
 2010840884,
 80084553,
 156983673,
 2507010098,
 2604879753,
 2044764759,
 193162130,
 4283272198,
 2070147155,
 3122420933,
 2381079051,
 2317126958,
 2396179459,
 2295146924,
 2093141983,
 2076764782,
 1261710638,
 1969860355,
 1992458738,
 1530475701,
 2151780953,
 2344917787,
 2736012731,
 201001518,
 2032296713,
 2322423610,
 2116052628,
 1492993235,
 1538569303,
 2372135098,
 2072547076,
 2884177126,
 2956062805,
 2114441064,
 4242181985,
 2041990407,
 1964194266,
 2374525880,
 2012270471,
 1897343572,
 2471491525,
 2353919845,
 2415762220,
 2938439978,
 1500349486,
 2131249368,
 2363427240,
 1999394493,
 3038208115,
 4280644088,
 2037416576,
 2800158533,
 632411667,
 2094134518,
 123589319,
 2595548090,
 2077815224,
 2773437713,
 1992418391,
 2390479218,
 1561245407,
 2035796389,
 2163442963,
 2198220867,
 2736953701,
 2266706080,
 94036611,
 1575119501,
 2778472217,
 4235303417,
 1969878310,
 1580507413,
 1498030985,
 2885984169,
 1607375837,
 2026979177,
 2044973203,
 2313441439,
 2516235021,
 2181548584,
 2107847257,
 2070456516,
 2132200325,
 2369191926,
 25797364,
 2093369451,
 2388234276,
 2020051109,
 2363613129,
 1975437988,
 2999462153,
 2017890221,
 2747102505,
 1606815746,
 1914855250,
 2013487298,
 3047378372,
 1546587844,
 1991494816,
 2433595228,
 2084867654,
 2527164916,
 2365238523,
 2597078000,
 3092758776,
 2128638906,
 844288681,
 2569632810,
 2089019629,
 1537720279,
 2009709647,
 2336488001,
 236412128,
 1978962506,
 2369753081,
 2062502251,
 2370376586,
 222802231,
 2012898383,
 2060800958,
 1606307309,
 1992209888,
 2189145255,
 1970693754,
 1861696976,
 2112195077,
 2247269301,
 3092394732,
 2092115118,
 23453599,
 2004624818,
 152498918,
 2092321355,
 2955646295,
 2133813185,
 1788149443,
 1981535150,
 2343274368,
 2367713799,
 2413671770,
 2381004058,
 1600433043,
 3151655128,
 2057222669,
 2181398105,
 2799574718,
 1965930941,
 2383668088,
 188470454,
 3165906843,
 2393185433,
 2222150373,
 2765294672,
 2188986695,
 1971918336,
 2359838292,
 89716039,
 2390314660,
 2156767027,
 1985398230,
 2061227503,
 2583721599,
 2549556143,
 2115990472,
 2394262714,
 141205568,
 1981061054,
 1997289888,
 3195659182,
 1686518172,
 1550960852,
 2368344660,
 2590975641,
 2378646356,
 3140347513,
 4234237066,
 2403178034,
 2484803068,
 2067086428,
 1817452857,
 2279992340,
 2001398454,
 2166901111,
 1790828723,
 2276447972,
 2379204095,
 3093765110,
 2553604968,
 2323780578,
 1990553614,
 2016376509,
 2066586841,
 1168333135,
 2140877893,
 2370930249,
 4246126998,
 2128117450,
 2375381701,
 1490525874,
 2114012898,
 2046478803,
 1492213150,
 2088162927,
 2337827596,
 1855907161,
 1567607914,
 1714971523,
 1766081903,
 3153952317,
 2169861160,
 2008658676,
 2305592738,
 2243924905,
 2797371907,
 1558929798,
 2210353698,
 2619312837,
 4239876960,
 2379424179,
 2149027946,
 2042986194,
 2383820259,
 2490220365,
 1983998071,
 205993195,
 2606579143,
 2136269533,
 1801334096,
 2462219636,
 2727511688,
 2064759747,
 617184199,
 2023378853,
 2920610587,
 127421644,
 2278374281,
 2325964005,
 2030828861,
 845481031,
 2485962012,
 1505500345,
 2389470923,
 2992836933,
 2531380506,
 2516107408,
 1964229157,
 2386167470,
 2024481244,
 4210891483,
 2586303491,
 2287447517,
 2151924907,
 1882854624,
 ...]

In [11]:
# 6min
# (B) 引用先の論文の抽出
B_relations = references_df[references_df['CitedPublicationId'].isin(bibmet_id_list)]

# (C) 参考文献に挙げた論文
C_relations = references_df[references_df['CitingPublicationId'].isin(bibmet_id_list)]

# (D) 更に「参考文献に挙げた論文」を参考文献に挙げている論文の抽出
# まず(C)からCitedPublicationIdを取得し、それを引用している論文を探す
C_cited_ids = C_relations['CitedPublicationId'].unique()
D_relations = references_df[references_df['CitedPublicationId'].isin(C_cited_ids)]

B_relations, D_relations

(        CitingPublicationId CitedPublicationId
 95               3117235547         3114353274
 47               2147314816         2147486095
 975              1992508126         1544177623
 57               2099334955         2172011800
 204              2085066400         2137817507
 ...                     ...                ...
 9434797          2134000226         1974362877
 9435026          2134132553         2078226033
 9435067          2134154704         1971449037
 9435815          2134438334         2096531787
 9436043          2134555933         2004159134

 [3072521 rows x 2 columns],
         CitingPublicationId CitedPublicationId
 2                3117235547         1540739244
 6                3117235547         1817976406
 8                3117235547         1911154180
 9                3117235547         1938062671
 14               3117235547         2004341664
 ...                     ...                ...
 9436461          2134806910         2142999685
 9436462          2134806910         2143114368
 9436463          2134806910         2158058159
 9436465          2134806910         4292994367
 9436471          2134809571         2040361811

 [429313279 rows x 2 columns])

In [12]:
# D_relations[D_relations['CitedPublicationId'] == 1976880180]

In [13]:
# D_relations[D_relations['CitingPublicationId'] == 2573593301]

In [14]:
# references_df[references_df['CitedPublicationId'] == 55183993]

In [15]:
# references_df[references_df['CitedPublicationId'] == '55183993']

In [16]:
works_rel_ref_df = pd.concat([B_relations, C_relations, D_relations]).drop_duplicates().reset_index(drop=True)
works_rel_ref_df.rename(columns={'CitingPublicationId': 'source', 'CitedPublicationId': 'target'}, inplace=True)
works_rel_ref_df

               source      target
0          3117235547  3114353274
1          2147314816  2147486095
2          1992508126  1544177623
3          2099334955  2172011800
4          2085066400  2137817507
...               ...         ...
431578945  2134806910  2142999685
431578946  2134806910  2143114368
431578947  2134806910  2158058159
431578948  2134806910  4292994367
431578949  2134809571  2040361811

[431578950 rows x 2 columns]

In [17]:
random_works_df.set_index('PublicationId', inplace=True)
random_works_df

,JournalId,Year,NumberCitations,Title,Date,DocType,Doi,PMID,Volume,Issue,FirstPage,LastPage,IsRetracted,IsParaText,AuthorCount
PublicationId,,,,,,,,,,,,,,,
3187609235,NaN,2020,0,Des choix contraires à la transition écologiqu...,2020-01-01,article,NaN,NaN,NaN,85,46,46,False,False,2.0
2266400421,NaN,1989,0,Ballade pour Frédéric. Piano,1989-01-01,article,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.0
2242094754,NaN,2005,0,Understanding what child protection data mean:...,2005-08-11,article,NaN,NaN,NaN,NaN,NaN,NaN,False,False,2.0
2951317825,NaN,2015,0,Desvendando o Universo com o Céu da Serra Gaúcha,2015-11-30,article,NaN,NaN,3,3,NaN,NaN,False,False,4.0
3030572269,NaN,2018,0,The estrogen deficiency hypothesis of schizoph...,2018-12-05,article,10.3760/cma.j.issn.1006-7884.2018.06.010,NaN,51,6,385,388,False,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1698120224,NaN,2002,25,NaN,2002-01-01,article,10.1023/a:1020616324734,NaN,69,3,897,904,False,False,3.0
2024816949,NaN,2011,27,A Quality-of-Life Comparison Between Self-Alig...,2011-04-01,article,10.1563/aaid-joi-d-10-00070,20662674,37,sp1,167,173,False,False,4.0
2040609328,NaN,1961,25,INFRARED STUDIES ON PYRROLES. THE STRUCTURE OF...,1961-04-01,article,10.1021/j100822a008,NaN,65,4,624,628,False,False,2.0
124423791,NaN,1986,26,Paleomagnetism in Arcuate Mountain Belts,1986-01-01,book-chapter,10.1016/b978-0-444-42688-8.50012-6,NaN,NaN,NaN,141,158,False,False,2.0
2119546324,NaN,1971,26,ANTI-EMETIC AND PROPULSIVE PERISTALTIC PROPERT...,1971-04-01,article,10.1093/bja/43.4.400,4930207,43,4,400,403,False,False,2.0

In [18]:
random_works_df.to_pickle(OUTPUT_WORKS_DF_PKL)
works_rel_ref_df.to_pickle(OUTPUT_WORKS_REL_REF_DF_PKL)